version: '3.1'

services:
    omniboard:
        image: vivekratnavel/omniboard
        command: ['--mu', 'mongodb://${MONGO_USER}:${MONGO_PASS}@mongo:27017/${MONGO_DB}?authSource=admin']
        ports:
            - 9000:9000
        depends_on:
            - mongo

    mongo:
        image: mongo
        restart: always
        volumes:
            - data:/data/db
        ports:
            - 27017:27017
        environment:
            MONGO_INITDB_DATABASE: ${MONGO_DB}
            MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
            MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASS}

volumes:
    data:
